
- name: create rsyslog.d
  become: yes
  file:
    dest: /etc/rsyslog.d
    state: directory
  tags:
    - docker
    - bootstrap

- name: create docker entry for syslogd
  become: yes
  copy:
    dest: /etc/rsyslog.d/10-docker.conf
    content: |
      # Docker logging
      :syslogtag, isequal, "docker:"  /var/log/docker/docker.log
      & ~
  notify:
    - restart rsyslog
  tags:
    - docker
    - bootstrap

- include_tasks: upstart-init.yml
  when: ansible_service_mgr != 'systemd'

- include_tasks: systemd-init.yml
  when: ansible_service_mgr == 'systemd'

- name: Ensure docker config dir exists
  become: yes
  file:
    path: /root/.docker
    state: directory
  tags:
    - docker

- name: Setup private docker registry credentials
  become: yes
  when: do_private_docker_registry
  template:
    src: config.json.j2
    dest: /root/.docker/config.json
  tags:
    - docker
  register: docker_registry_credentials

- name: Add docker registry credentials to /etc/
  become: yes
  when: do_private_docker_registry and docker_registry_credentials.changed
  command: tar cvzf /etc/docker.tar.gz .docker
  args:
    chdir: /root
  tags:
    - docker
    - skip_ansible_lint
