---

- include_vars: "{{ ansible_os_family }}.yml"

- name: Create docker group
  group: name=docker state=present system=yes
  when: docker_create_group
  tags:
    - config

- include: init.yml

- name: Ensure that the new configuration has been loaded
  meta: flush_handlers

- include: Debian.yml
  when: ansible_os_family == "Debian"

- include: RedHat.yml
  when: ansible_os_family == "RedHat"

- name: Enable docker
  become: yes
  service:
    name: docker
    enabled: yes
    state: started
  tags:
    - docker
    - bootstrap # needed to install Docker images during bootstrap
