---

- include_vars: "{{ ansible_os_family }}.yml"

- name: Create docker group
  group: name=docker state=present system=yes
  when: docker_create_group
  tags:
    - config

- import_tasks: init.yml

- name: Ensure that the new configuration has been loaded
  meta: flush_handlers

- include_tasks: Debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: RedHat.yml
  when: ansible_os_family == "RedHat"

- name: Start Docker
  become: yes
  service:
    name: docker
    enabled: yes
    state: started
  tags:
    - docker
    - bootstrap # needed to install Docker images during bootstrap

- name: Ensure that Docker has started and keeps running
  service: name=docker state=started
  tags:
    - docker
    - bootstrap # needed to install Docker images during bootstrap
  register: docker_running
  until: docker_running.state == 'started' and not docker_running is changed
  retries: 2
  delay: 5

- name: Validate that Docker is running
  fail:
    msg: >
      Service docker has not started as expected, please check its current status or error messages
  when: docker_running.state != 'started' or docker_running is changed
  tags:
    - docker
    - bootstrap # needed to install Docker images during bootstrap
