---

- name: Docker upstart default config file
  template: src=docker-defaults.j2 dest=/etc/default/docker
  notify:
    - restart docker

- name: Docker init file
  template: src=docker-init.j2 dest=/etc/init/docker.conf
  notify:
    - restart docker
